version: '3.8'

services:
  database:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: rachit
      POSTGRES_USER: rachit
      POSTGRES_DB: flask_api

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:5000 app:app
    expose:
      - 80
    restart: always
    depends_on:
      - database
    links:
      - "database"
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web